"""Initial migration

Revision ID: 35dd8bd8e211
Revises: 
Create Date: 2024-06-14 14:21:26.849882

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '35dd8bd8e211'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('is_visible', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_categories_id'), 'categories', ['id'], unique=False)
    op.create_table('goods',
    sa.Column('nm_id', sa.Integer(), nullable=False),
    sa.Column('vendor_code', sa.String(), nullable=True),
    sa.Column('currency_iso_code', sa.String(), nullable=True),
    sa.Column('discount', sa.Integer(), nullable=True),
    sa.Column('date_received', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('nm_id')
    )
    op.create_index(op.f('ix_goods_nm_id'), 'goods', ['nm_id'], unique=False)
    op.create_table('incomes',
    sa.Column('income_id', sa.Integer(), nullable=False),
    sa.Column('number', sa.String(), nullable=True),
    sa.Column('date', sa.String(), nullable=True),
    sa.Column('last_change_date', sa.String(), nullable=True),
    sa.Column('supplier_article', sa.String(), nullable=True),
    sa.Column('tech_size', sa.String(), nullable=True),
    sa.Column('barcode', sa.String(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('total_price', sa.Float(), nullable=True),
    sa.Column('date_close', sa.String(), nullable=True),
    sa.Column('warehouse_name', sa.String(), nullable=True),
    sa.Column('nm_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('income_id')
    )
    op.create_index(op.f('ix_incomes_income_id'), 'incomes', ['income_id'], unique=False)
    op.create_table('orders',
    sa.Column('date', sa.String(), nullable=True),
    sa.Column('last_change_date', sa.String(), nullable=True),
    sa.Column('warehouse_name', sa.String(), nullable=True),
    sa.Column('country_name', sa.String(), nullable=True),
    sa.Column('oblast_okrug_name', sa.String(), nullable=True),
    sa.Column('region_name', sa.String(), nullable=True),
    sa.Column('supplier_article', sa.String(), nullable=True),
    sa.Column('nm_id', sa.Integer(), nullable=False),
    sa.Column('barcode', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('subject', sa.String(), nullable=True),
    sa.Column('brand', sa.String(), nullable=True),
    sa.Column('tech_size', sa.String(), nullable=True),
    sa.Column('income_id', sa.Integer(), nullable=True),
    sa.Column('is_supply', sa.Boolean(), nullable=True),
    sa.Column('is_realization', sa.Boolean(), nullable=True),
    sa.Column('total_price', sa.Float(), nullable=True),
    sa.Column('discount_percent', sa.Integer(), nullable=True),
    sa.Column('spp', sa.Float(), nullable=True),
    sa.Column('finished_price', sa.Float(), nullable=True),
    sa.Column('price_with_disc', sa.Float(), nullable=True),
    sa.Column('is_cancel', sa.Boolean(), nullable=True),
    sa.Column('cancel_date', sa.String(), nullable=True),
    sa.Column('order_type', sa.String(), nullable=True),
    sa.Column('sticker', sa.String(), nullable=True),
    sa.Column('g_number', sa.String(), nullable=True),
    sa.Column('srid', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('nm_id')
    )
    op.create_table('sales',
    sa.Column('date', sa.String(), nullable=True),
    sa.Column('last_change_date', sa.String(), nullable=True),
    sa.Column('warehouse_name', sa.String(), nullable=True),
    sa.Column('country_name', sa.String(), nullable=True),
    sa.Column('oblast_okrug_name', sa.String(), nullable=True),
    sa.Column('region_name', sa.String(), nullable=True),
    sa.Column('supplier_article', sa.String(), nullable=True),
    sa.Column('nm_id', sa.Integer(), nullable=False),
    sa.Column('barcode', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('subject', sa.String(), nullable=True),
    sa.Column('brand', sa.String(), nullable=True),
    sa.Column('tech_size', sa.String(), nullable=True),
    sa.Column('income_id', sa.Integer(), nullable=True),
    sa.Column('is_supply', sa.Boolean(), nullable=True),
    sa.Column('is_realization', sa.Boolean(), nullable=True),
    sa.Column('total_price', sa.Float(), nullable=True),
    sa.Column('discount_percent', sa.Integer(), nullable=True),
    sa.Column('spp', sa.Float(), nullable=True),
    sa.Column('payment_sale_amount', sa.Integer(), nullable=True),
    sa.Column('for_pay', sa.Float(), nullable=True),
    sa.Column('finished_price', sa.Float(), nullable=True),
    sa.Column('price_with_disc', sa.Float(), nullable=True),
    sa.Column('sale_id', sa.String(), nullable=False),
    sa.Column('order_type', sa.String(), nullable=True),
    sa.Column('sticker', sa.String(), nullable=True),
    sa.Column('g_number', sa.String(), nullable=True),
    sa.Column('srid', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('nm_id', 'sale_id')
    )
    op.create_index(op.f('ix_sales_sale_id'), 'sales', ['sale_id'], unique=False)
    op.create_table('sellers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('api_key', sa.String(), nullable=True),
    sa.Column('subscription_level', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sellers_id'), 'sellers', ['id'], unique=False)
    op.create_index(op.f('ix_sellers_name'), 'sellers', ['name'], unique=True)
    op.create_table('stocks',
    sa.Column('sku', sa.String(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('sku')
    )
    op.create_index(op.f('ix_stocks_sku'), 'stocks', ['sku'], unique=False)
    op.create_table('subcategories',
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('subject_name', sa.String(), nullable=True),
    sa.Column('parent_name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('subject_id')
    )
    op.create_index(op.f('ix_subcategories_subject_id'), 'subcategories', ['subject_id'], unique=False)
    op.create_table('supplier_stocks',
    sa.Column('last_change_date', sa.String(), nullable=True),
    sa.Column('warehouse_name', sa.String(), nullable=True),
    sa.Column('supplier_article', sa.String(), nullable=True),
    sa.Column('nm_id', sa.Integer(), nullable=False),
    sa.Column('barcode', sa.String(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('in_way_to_client', sa.Integer(), nullable=True),
    sa.Column('in_way_from_client', sa.Integer(), nullable=True),
    sa.Column('quantity_full', sa.Integer(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('subject', sa.String(), nullable=True),
    sa.Column('brand', sa.String(), nullable=True),
    sa.Column('tech_size', sa.String(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('discount', sa.Float(), nullable=True),
    sa.Column('is_supply', sa.Boolean(), nullable=True),
    sa.Column('is_realization', sa.Boolean(), nullable=True),
    sa.Column('sc_code', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('nm_id')
    )
    op.create_table('expenses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('seller_id', sa.Integer(), nullable=True),
    sa.Column('item_name', sa.String(), nullable=True),
    sa.Column('ad_cost', sa.Float(), nullable=True),
    sa.Column('photo_cost', sa.Float(), nullable=True),
    sa.Column('salary_cost', sa.Float(), nullable=True),
    sa.Column('other_cost', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['seller_id'], ['sellers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_expenses_id'), 'expenses', ['id'], unique=False)
    op.create_table('sizes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('good_nm_id', sa.Integer(), nullable=True),
    sa.Column('size_id', sa.Integer(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('discounted_price', sa.Float(), nullable=True),
    sa.Column('tech_size_name', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['good_nm_id'], ['goods.nm_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sizes_id'), 'sizes', ['id'], unique=False)
    op.alter_column('report_details', 'realizationreport_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.drop_index('ix_report_details_id', table_name='report_details')
    op.create_index(op.f('ix_report_details_realizationreport_id'), 'report_details', ['realizationreport_id'], unique=False)
    op.drop_column('report_details', 'rebill_logistic_cost')
    op.drop_column('report_details', 'ppvz_reward')
    op.drop_column('report_details', 'ppvz_for_pay')
    op.drop_column('report_details', 'acquiring_bank')
    op.drop_column('report_details', 'sup_rating_prc_up')
    op.drop_column('report_details', 'is_kgvp_v2')
    op.drop_column('report_details', 'acquiring_fee')
    op.drop_column('report_details', 'bonus_type_name')
    op.drop_column('report_details', 'ppvz_vw_nds')
    op.drop_column('report_details', 'ppvz_sales_commission')
    op.drop_column('report_details', 'rebill_logistic_org')
    op.drop_column('report_details', 'id')
    op.drop_column('report_details', 'ppvz_vw')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('report_details', sa.Column('ppvz_vw', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('report_details', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.add_column('report_details', sa.Column('rebill_logistic_org', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('report_details', sa.Column('ppvz_sales_commission', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('report_details', sa.Column('ppvz_vw_nds', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('report_details', sa.Column('bonus_type_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('report_details', sa.Column('acquiring_fee', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('report_details', sa.Column('is_kgvp_v2', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('report_details', sa.Column('sup_rating_prc_up', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('report_details', sa.Column('acquiring_bank', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('report_details', sa.Column('ppvz_for_pay', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('report_details', sa.Column('ppvz_reward', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('report_details', sa.Column('rebill_logistic_cost', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_report_details_realizationreport_id'), table_name='report_details')
    op.create_index('ix_report_details_id', 'report_details', ['id'], unique=False)
    op.alter_column('report_details', 'realizationreport_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.drop_index(op.f('ix_sizes_id'), table_name='sizes')
    op.drop_table('sizes')
    op.drop_index(op.f('ix_expenses_id'), table_name='expenses')
    op.drop_table('expenses')
    op.drop_table('supplier_stocks')
    op.drop_index(op.f('ix_subcategories_subject_id'), table_name='subcategories')
    op.drop_table('subcategories')
    op.drop_index(op.f('ix_stocks_sku'), table_name='stocks')
    op.drop_table('stocks')
    op.drop_index(op.f('ix_sellers_name'), table_name='sellers')
    op.drop_index(op.f('ix_sellers_id'), table_name='sellers')
    op.drop_table('sellers')
    op.drop_index(op.f('ix_sales_sale_id'), table_name='sales')
    op.drop_table('sales')
    op.drop_table('orders')
    op.drop_index(op.f('ix_incomes_income_id'), table_name='incomes')
    op.drop_table('incomes')
    op.drop_index(op.f('ix_goods_nm_id'), table_name='goods')
    op.drop_table('goods')
    op.drop_index(op.f('ix_categories_id'), table_name='categories')
    op.drop_table('categories')
    # ### end Alembic commands ###
